// System theme detection and sync
function getSystemTheme() {
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}

// Set initial theme based on system preference if no saved theme
if (!localStorage.getItem('theme')) {
    document.documentElement.setAttribute('data-theme', getSystemTheme());
}

// Listen for system theme changes
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
    if (!localStorage.getItem('theme')) {
        document.documentElement.setAttribute('data-theme', e.matches ? 'dark' : 'light');
    }
});

// header links
document.getElementById('getcyber').addEventListener('click', () => {
    window.open('https://getcyber.me', '_blank');
});

document.getElementById('github').addEventListener('click', () => {
    window.open('https://github.com/Dan-Duran/emoji-world', '_blank');
});

document.getElementById('youtube-subscribe').addEventListener('click', () => {
    window.open('https://youtube.com/@GetCyber', '_blank');
});

document.getElementById('discord-join').addEventListener('click', () => {
    window.open('https://discord.gg/YUf3VpDeNH', '_blank');
});

const emojiCategories = {
    'Popular': [
    { char: '😂', name: 'face with tears of joy' },
    { char: '❤️', name: 'red heart' },
    { char: '🤣', name: 'rolling on the floor laughing' },
    { char: '👍', name: 'thumbs up' },
    { char: '😭', name: 'loudly crying face' },
    { char: '🙏', name: 'folded hands' },
    { char: '😘', name: 'face blowing a kiss' },
    { char: '🥰', name: 'smiling face with hearts' },
    { char: '😍', name: 'smiling face with heart-eyes' },
    { char: '✨', name: 'sparkles' },
    { char: '🔥', name: 'fire' },
    { char: '😊', name: 'smiling face with smiling eyes' },
    { char: '🎉', name: 'party popper' },
    { char: '💕', name: 'two hearts' },
    { char: '🥺', name: 'pleading face' },
    { char: '💯', name: 'hundred points' },
    ],
    'Smileys & Emotion': [
    { char: '😀', name: 'grinning face' },
    { char: '😃', name: 'grinning face with big eyes' },
    { char: '😄', name: 'grinning face with smiling eyes' },
    { char: '😁', name: 'beaming face with smiling eyes' },
    { char: '😆', name: 'grinning squinting face' },
    { char: '😅', name: 'grinning face with sweat' },
    { char: '🤣', name: 'rolling on the floor laughing' },
    { char: '😂', name: 'face with tears of joy' },
    { char: '🙂', name: 'slightly smiling face' },
    { char: '🙃', name: 'upside-down face' },
    { char: '😉', name: 'winking face' },
    { char: '😊', name: 'smiling face with smiling eyes' },
    { char: '😇', name: 'smiling face with halo' },
    { char: '🥰', name: 'smiling face with hearts' },
    { char: '😍', name: 'smiling face with heart-eyes' },
    { char: '🤩', name: 'star-struck' },
    { char: '😘', name: 'face blowing a kiss' },
    { char: '😗', name: 'kissing face' },
    { char: '☺️', name: 'smiling face' },
    { char: '😚', name: 'kissing face with closed eyes' },
    { char: '😙', name: 'kissing face with smiling eyes' },
    { char: '🥲', name: 'smiling face with tear' },
    { char: '😋', name: 'face savoring food' },
    { char: '😛', name: 'face with tongue' },
    { char: '😜', name: 'winking face with tongue' },
    { char: '🤪', name: 'zany face' },
    { char: '😝', name: 'squinting face with tongue' },
    { char: '🤑', name: 'money-mouth face' },
    { char: '🤗', name: 'smiling face with open hands' },
    { char: '🤭', name: 'face with hand over mouth' },
    { char: '🫢', name: 'face with open eyes and hand over mouth' },
    { char: '🫣', name: 'face with peeking eye' },
    { char: '🤫', name: 'shushing face' },
    { char: '🤔', name: 'thinking face' },
    { char: '🫡', name: 'saluting face' },
    { char: '🤐', name: 'zipper-mouth face' },
    { char: '🤨', name: 'face with raised eyebrow' },
    { char: '😐', name: 'neutral face' },
    { char: '😑', name: 'expressionless face' },
    { char: '😶', name: 'face without mouth' },
    { char: '🫥', name: 'dotted line face' },
    { char: '😶‍🌫️', name: 'face in clouds' },
    { char: '😏', name: 'smirking face' },
    { char: '😒', name: 'unamused face' },
    { char: '🙄', name: 'face with rolling eyes' },
    { char: '😬', name: 'grimacing face' },
    { char: '😮‍💨', name: 'face exhaling' },
    { char: '🤥', name: 'lying face' },
    { char: '😌', name: 'relieved face' },
    { char: '😔', name: 'pensive face' },
    { char: '😪', name: 'sleepy face' },
    { char: '🤤', name: 'drooling face' },
    { char: '😴', name: 'sleeping face' },
    { char: '😷', name: 'face with medical mask' },
    { char: '🤒', name: 'face with thermometer' },
    { char: '🤕', name: 'face with head-bandage' },
    { char: '🤢', name: 'nauseated face' },
    { char: '🤮', name: 'face vomiting' },
    { char: '🤧', name: 'sneezing face' },
    { char: '🥵', name: 'hot face' },
    { char: '🥶', name: 'cold face' },
    { char: '🥴', name: 'woozy face' },
    { char: '😵', name: 'dizzy face' },
    { char: '😵‍💫', name: 'face with spiral eyes' },
    { char: '🤯', name: 'exploding head' },
    { char: '🤠', name: 'cowboy hat face' },
    { char: '🥳', name: 'partying face' },
    { char: '🥸', name: 'disguised face' },
    { char: '😎', name: 'smiling face with sunglasses' },
    { char: '🤓', name: 'nerd face' },
    { char: '🧐', name: 'face with monocle' },
    { char: '😕', name: 'confused face' },
    { char: '🫤', name: 'face with diagonal mouth' },
    { char: '😟', name: 'worried face' },
    { char: '🙁', name: 'slightly frowning face' },
    { char: '☹️', name: 'frowning face' },
    { char: '😮', name: 'face with open mouth' },
    { char: '😯', name: 'hushed face' },
    { char: '😲', name: 'astonished face' },
    { char: '😳', name: 'flushed face' },
    { char: '🥺', name: 'pleading face' },
    { char: '🥹', name: 'face holding back tears' },
    { char: '😦', name: 'frowning face with open mouth' },
    { char: '😧', name: 'anguished face' },
    { char: '😨', name: 'fearful face' },
    { char: '😰', name: 'anxious face with sweat' },
    { char: '😥', name: 'sad but relieved face' },
    { char: '😢', name: 'crying face' },
    { char: '😭', name: 'loudly crying face' },
    { char: '😱', name: 'face screaming in fear' },
    { char: '😖', name: 'confounded face' },
    { char: '😣', name: 'persevering face' },
    { char: '😞', name: 'disappointed face' },
    { char: '😓', name: 'downcast face with sweat' },
    { char: '😩', name: 'weary face' },
    { char: '😫', name: 'tired face' },
    { char: '🥱', name: 'yawning face' },
    { char: '😤', name: 'face with steam from nose' },
    { char: '😡', name: 'pouting face' },
    { char: '😠', name: 'angry face' },
    { char: '🤬', name: 'face with symbols on mouth' },
    { char: '😈', name: 'smiling face with horns' },
    { char: '👿', name: 'angry face with horns' },
    { char: '💀', name: 'skull' },
    { char: '☠️', name: 'skull and crossbones' },
    { char: '💩', name: 'pile of poo' },
    { char: '🤡', name: 'clown face' },
    { char: '👹', name: 'ogre' },
    { char: '👺', name: 'goblin' },
    { char: '👻', name: 'ghost' },
    { char: '👽', name: 'alien' },
    { char: '👾', name: 'alien monster' },
    { char: '🤖', name: 'robot' },
    { char: '🫢', name: 'face with open eyes and hand over mouth' },
    { char: '🫣', name: 'face with peeking eye' },
    { char: '🫡', name: 'saluting face' },
    { char: '🫥', name: 'dotted line face' },
    { char: '🥹', name: 'face holding back tears' },
    { char: '😮‍💨', name: 'face exhaling' },
    { char: '😵‍💫', name: 'face with spiral eyes' },
    { char: '😶‍🌫️', name: 'face in clouds' },
    { char: '🫨', name: 'shaking face' },
    { char: '🥱', name: 'yawning face' },
    { char: '❤️', name: 'red heart' },
    { char: '🧡', name: 'orange heart' },
    { char: '💛', name: 'yellow heart' },
    { char: '💚', name: 'green heart' },
    { char: '💙', name: 'blue heart' },
    { char: '💜', name: 'purple heart' },
    { char: '🤎', name: 'brown heart' },
    { char: '🖤', name: 'black heart' },
    { char: '🤍', name: 'white heart' },
    { char: '💔', name: 'broken heart' },
    { char: '❤️‍🔥', name: 'heart on fire' },
    { char: '❤️‍🩹', name: 'mending heart' },
    { char: '💝', name: 'heart with ribbon' },
    { char: '💖', name: 'sparkling heart' },
    { char: '💗', name: 'growing heart' },
    { char: '💓', name: 'beating heart' },
    { char: '💞', name: 'revolving hearts' },
    { char: '💕', name: 'two hearts' },
    { char: '💘', name: 'heart with arrow' },
    { char: '💌', name: 'love letter' }
    ],
    'People & Body': [
    { char: '👋', name: 'waving hand' },
    { char: '🤚', name: 'raised back of hand' },
    { char: '🖐️', name: 'hand with fingers splayed' },
    { char: '✋', name: 'raised hand' },
    { char: '🖖', name: 'vulcan salute' },
    { char: '🫱', name: 'rightwards hand' },
    { char: '🫲', name: 'leftwards hand' },
    { char: '🫳', name: 'palm down hand' },
    { char: '🫴', name: 'palm up hand' },
    { char: '👌', name: 'OK hand' },
    { char: '🤌', name: 'pinched fingers' },
    { char: '🤏', name: 'pinching hand' },
    { char: '✌️', name: 'victory hand' },
    { char: '🤞', name: 'crossed fingers' },
    { char: '🫰', name: 'hand with index finger and thumb crossed' },
    { char: '🤟', name: 'love-you gesture' },
    { char: '🤘', name: 'sign of the horns' },
    { char: '🤙', name: 'call me hand' },
    { char: '👈', name: 'backhand index pointing left' },
    { char: '👉', name: 'backhand index pointing right' },
    { char: '👆', name: 'backhand index pointing up' },
    { char: '🖕', name: 'middle finger' },
    { char: '👇', name: 'backhand index pointing down' },
    { char: '☝️', name: 'index pointing up' },
    { char: '🫵', name: 'index pointing at the viewer' },
    { char: '👍', name: 'thumbs up' },
    { char: '👎', name: 'thumbs down' },
    { char: '✊', name: 'raised fist' },
    { char: '👊', name: 'oncoming fist' },
    { char: '🤛', name: 'left-facing fist' },
    { char: '🤜', name: 'right-facing fist' },
    { char: '👏', name: 'clapping hands' },
    { char: '🙌', name: 'raising hands' },
    { char: '🫶', name: 'heart hands' },
    { char: '👐', name: 'open hands' },
    { char: '🤲', name: 'palms up together' },
    { char: '🤝', name: 'handshake' },
    { char: '🙏', name: 'folded hands' },
    { char: '✍️', name: 'writing hand' },
    { char: '💅', name: 'nail polish' },
    { char: '🤳', name: 'selfie' },
    { char: '💪', name: 'flexed biceps' },
    { char: '🦾', name: 'mechanical arm' },
    { char: '🦿', name: 'mechanical leg' },
    { char: '🦵', name: 'leg' },
    { char: '🦶', name: 'foot' },
    { char: '👂', name: 'ear' },
    { char: '🦻', name: 'ear with hearing aid' },
    { char: '👃', name: 'nose' },
    { char: '🧠', name: 'brain' },
    { char: '🫀', name: 'anatomical heart' },
    { char: '🫁', name: 'lungs' },
    { char: '🦷', name: 'tooth' },
    { char: '🦴', name: 'bone' },
    { char: '👀', name: 'eyes' },
    { char: '👁️', name: 'eye' },
    { char: '👅', name: 'tongue' },
    { char: '👄', name: 'mouth' },
    { char: '🫦', name: 'biting lip' },
    { char: '👶', name: 'baby' },
    { char: '🧒', name: 'child' },
    { char: '👦', name: 'boy' },
    { char: '👧', name: 'girl' },
    { char: '🧑', name: 'person' },
    { char: '👱', name: 'person with blond hair' },
    { char: '👨', name: 'man' },
    { char: '🧔', name: 'person with beard' },
    { char: '👩', name: 'woman' },
    { char: '🧓', name: 'older person' },
    { char: '👴', name: 'old man' },
    { char: '👵', name: 'old woman' },
    { char: '🙍', name: 'person frowning' },
    { char: '🙎', name: 'person pouting' },
    { char: '🙅', name: 'person gesturing NO' },
    { char: '🙆', name: 'person gesturing OK' },
    { char: '💁', name: 'person tipping hand' },
    { char: '🙋', name: 'person raising hand' },
    { char: '🧏', name: 'deaf person' },
    { char: '🙇', name: 'person bowing' },
    { char: '🤦', name: 'person facepalming' },
    { char: '🤷', name: 'person shrugging' },
    { char: '👮', name: 'police officer' },
    { char: '🕵️', name: 'detective' },
    { char: '💂', name: 'guard' },
    { char: '🥷', name: 'ninja' },
    { char: '👷', name: 'construction worker' },
    { char: '🤴', name: 'prince' },
    { char: '👸', name: 'princess' },
    { char: '👳', name: 'person wearing turban' },
    { char: '👲', name: 'person with skullcap' },
    { char: '🧕', name: 'woman with headscarf' },
    { char: '🤵', name: 'person in tuxedo' },
    { char: '👰', name: 'person with veil' },
    { char: '🤰', name: 'pregnant woman' },
    { char: '🫃', name: 'pregnant man' },
    { char: '🫄', name: 'pregnant person' },
    { char: '🤱', name: 'breast-feeding' },
    { char: '👼', name: 'baby angel' },
    { char: '🎅', name: 'Santa Claus' },
    { char: '🤶', name: 'Mrs. Claus' },
    { char: '🦸', name: 'superhero' },
    { char: '🦹', name: 'supervillain' },
    { char: '🧙', name: 'mage' },
    { char: '🧚', name: 'fairy' },
    { char: '🧛', name: 'vampire' },
    { char: '🧜', name: 'merperson' },
    { char: '🧝', name: 'elf' },
    { char: '🧞', name: 'genie' },
    { char: '🧟', name: 'zombie' },
    { char: '💆', name: 'person getting massage' },
    { char: '💇', name: 'person getting haircut' },
    { char: '🚶', name: 'person walking' },
    { char: '🧍', name: 'person standing' },
    { char: '🧎', name: 'person kneeling' },
    { char: '🏃', name: 'person running' },
    { char: '💃', name: 'woman dancing' },
    { char: '🕺', name: 'man dancing' },
    { char: '🕴️', name: 'person in suit levitating' },
    { char: '👯', name: 'people with bunny ears' },
    { char: '🧖', name: 'person in steamy room' },
    { char: '🧗', name: 'person climbing' },
    { char: '🤺', name: 'person fencing' },
    { char: '🏇', name: 'horse racing' },
    { char: '⛷️', name: 'skier' },
    { char: '🏂', name: 'snowboarder' },
    { char: '🏌️', name: 'person golfing' },
    { char: '🏄', name: 'person surfing' },
    { char: '🚣', name: 'person rowing boat' },
    { char: '🏊', name: 'person swimming' },
    { char: '⛹️', name: 'person bouncing ball' },
    { char: '🏋️', name: 'person lifting weights' },
    { char: '🚴', name: 'person biking' },
    { char: '🚵', name: 'person mountain biking' },
    { char: '🤸', name: 'person cartwheeling' },
    { char: '🤼', name: 'people wrestling' },
    { char: '🤽', name: 'person playing water polo' },
    { char: '🤾', name: 'person playing handball' },
    { char: '🤹', name: 'person juggling' },
    { char: '🧘', name: 'person in lotus position' },
    { char: '👨‍👩‍👦', name: 'family: man, woman, boy' },
    { char: '👨‍👩‍👧', name: 'family: man, woman, girl' },
    { char: '👨‍👩‍👧‍👦', name: 'family: man, woman, girl, boy' },
    { char: '👨‍👩‍👦‍👦', name: 'family: man, woman, boy, boy' },
    { char: '👨‍👩‍👧‍👧', name: 'family: man, woman, girl, girl' },
    { char: '👨‍👨‍👦', name: 'family: man, man, boy' },
    { char: '👨‍👨‍👧', name: 'family: man, man, girl' },
    { char: '👨‍👨‍👧‍👦', name: 'family: man, man, girl, boy' },
    { char: '👨‍👨‍👦‍👦', name: 'family: man, man, boy, boy' },
    { char: '👨‍👨‍👧‍👧', name: 'family: man, man, girl, girl' },
    { char: '👩‍👩‍👦', name: 'family: woman, woman, boy' },
    { char: '👩‍👩‍👧', name: 'family: woman, woman, girl' },
    { char: '👩‍👩‍👧‍👦', name: 'family: woman, woman, girl, boy' },
    { char: '👩‍👩‍👦‍👦', name: 'family: woman, woman, boy, boy' },
    { char: '👩‍👩‍👧‍👧', name: 'family: woman, woman, girl, girl' },
    { char: '👨‍👦', name: 'family: man, boy' },
    { char: '👨‍👦‍👦', name: 'family: man, boy, boy' },
    { char: '👨‍👧', name: 'family: man, girl' },
    { char: '👨‍👧‍👦', name: 'family: man, girl, boy' },
    { char: '👨‍👧‍👧', name: 'family: man, girl, girl' },
    { char: '👩‍👦', name: 'family: woman, boy' },
    { char: '👩‍👦‍👦', name: 'family: woman, boy, boy' },
    { char: '👩‍👧', name: 'family: woman, girl' },
    { char: '👩‍👧‍👦', name: 'family: woman, girl, boy' },
    { char: '👩‍👧‍👧', name: 'family: woman, girl, girl' },
    { char: '👨‍⚕️', name: 'man health worker' },
    { char: '👩‍⚕️', name: 'woman health worker' },
    { char: '👨‍🎓', name: 'man student' },
    { char: '👩‍🎓', name: 'woman student' },
    { char: '👨‍🏫', name: 'man teacher' },
    { char: '👩‍🏫', name: 'woman teacher' },
    { char: '👨‍⚖️', name: 'man judge' },
    { char: '👩‍⚖️', name: 'woman judge' },
    { char: '👨‍🌾', name: 'man farmer' },
    { char: '👩‍🌾', name: 'woman farmer' },
    { char: '👨‍🍳', name: 'man cook' },
    { char: '👩‍🍳', name: 'woman cook' },
    { char: '👨‍🔧', name: 'man mechanic' },
    { char: '👩‍🔧', name: 'woman mechanic' },
    { char: '👨‍🏭', name: 'man factory worker' },
    { char: '👩‍🏭', name: 'woman factory worker' },
    { char: '👨‍💼', name: 'man office worker' },
    { char: '👩‍💼', name: 'woman office worker' },
    { char: '👨‍🔬', name: 'man scientist' },
    { char: '👩‍🔬', name: 'woman scientist' },
    { char: '👨‍💻', name: 'man technologist' },
    { char: '👩‍💻', name: 'woman technologist' },
    { char: '👨‍🎤', name: 'man singer' },
    { char: '👩‍🎤', name: 'woman singer' },
    { char: '👨‍🎨', name: 'man artist' },
    { char: '👩‍🎨', name: 'woman artist' },
    { char: '👨‍✈️', name: 'man pilot' },
    { char: '👩‍✈️', name: 'woman pilot' },
    { char: '👨‍🚀', name: 'man astronaut' },
    { char: '👩‍🚀', name: 'woman astronaut' },
    { char: '👨‍🚒', name: 'man firefighter' },
    { char: '👩‍🚒', name: 'woman firefighter' }
    ],
    'Animals & Nature': [
    { char: '🐵', name: 'monkey face' },
    { char: '🐒', name: 'monkey' },
    { char: '🦍', name: 'gorilla' },
    { char: '🦧', name: 'orangutan' },
    { char: '🐶', name: 'dog face' },
    { char: '🐕', name: 'dog' },
    { char: '🦮', name: 'guide dog' },
    { char: '🐕‍🦺', name: 'service dog' },
    { char: '🐩', name: 'poodle' },
    { char: '🐺', name: 'wolf' },
    { char: '🦊', name: 'fox' },
    { char: '🦝', name: 'raccoon' },
    { char: '🐱', name: 'cat face' },
    { char: '🐈', name: 'cat' },
    { char: '🐈‍⬛', name: 'black cat' },
    { char: '🦁', name: 'lion' },
    { char: '🐯', name: 'tiger face' },
    { char: '🐅', name: 'tiger' },
    { char: '🐆', name: 'leopard' },
    { char: '🐴', name: 'horse face' },
    { char: '🐎', name: 'horse' },
    { char: '🦄', name: 'unicorn' },
    { char: '🦓', name: 'zebra' },
    { char: '🦌', name: 'deer' },
    { char: '🦬', name: 'bison' },
    { char: '🐮', name: 'cow face' },
    { char: '🐂', name: 'ox' },
    { char: '🐃', name: 'water buffalo' },
    { char: '🐄', name: 'cow' },
    { char: '🐷', name: 'pig face' },
    { char: '🐖', name: 'pig' },
    { char: '🐗', name: 'boar' },
    { char: '🐽', name: 'pig nose' },
    { char: '🐏', name: 'ram' },
    { char: '🐑', name: 'ewe' },
    { char: '🐐', name: 'goat' },
    { char: '🐪', name: 'camel' },
    { char: '🐫', name: 'two-hump camel' },
    { char: '🦙', name: 'llama' },
    { char: '🦒', name: 'giraffe' },
    { char: '🐘', name: 'elephant' },
    { char: '🦣', name: 'mammoth' },
    { char: '🦏', name: 'rhinoceros' },
    { char: '🦛', name: 'hippopotamus' },
    { char: '🐭', name: 'mouse face' },
    { char: '🐁', name: 'mouse' },
    { char: '🐀', name: 'rat' },
    { char: '🐹', name: 'hamster' },
    { char: '🐰', name: 'rabbit face' },
    { char: '🐇', name: 'rabbit' },
    { char: '🐿️', name: 'chipmunk' },
    { char: '🦫', name: 'beaver' },
    { char: '🦔', name: 'hedgehog' },
    { char: '🦇', name: 'bat' },
    { char: '🐻', name: 'bear' },
    { char: '🐻‍❄️', name: 'polar bear' },
    { char: '🐨', name: 'koala' },
    { char: '🐼', name: 'panda' },
    { char: '🦘', name: 'kangaroo' },
    { char: '🦡', name: 'badger' },
    { char: '🦃', name: 'turkey' },
    { char: '🐔', name: 'chicken' },
    { char: '🐓', name: 'rooster' },
    { char: '🐣', name: 'hatching chick' },
    { char: '🐤', name: 'baby chick' },
    { char: '🐥', name: 'front-facing baby chick' },
    { char: '🐦', name: 'bird' },
    { char: '🐦‍⬛', name: 'black bird' },
    { char: '🦅', name: 'eagle' },
    { char: '🦆', name: 'duck' },
    { char: '🦢', name: 'swan' },
    { char: '🦉', name: 'owl' },
    { char: '🦤', name: 'dodo' },
    { char: '🪶', name: 'feather' },
    { char: '🦩', name: 'flamingo' },
    { char: '🦚', name: 'peacock' },
    { char: '🦜', name: 'parrot' },
    { char: '🐸', name: 'frog' },
    { char: '🐊', name: 'crocodile' },
    { char: '🐢', name: 'turtle' },
    { char: '🦎', name: 'lizard' },
    { char: '🐍', name: 'snake' },
    { char: '🐲', name: 'dragon face' },
    { char: '🐉', name: 'dragon' },
    { char: '🦕', name: 'sauropod' },
    { char: '🦖', name: 'T-Rex' },
    { char: '🐳', name: 'spouting whale' },
    { char: '🐋', name: 'whale' },
    { char: '🐬', name: 'dolphin' },
    { char: '🦭', name: 'seal' },
    { char: '🐟', name: 'fish' },
    { char: '🐠', name: 'tropical fish' },
    { char: '🐡', name: 'blowfish' },
    { char: '🦈', name: 'shark' },
    { char: '🐙', name: 'octopus' },
    { char: '🐚', name: 'spiral shell' },
    { char: '🪸', name: 'coral' },
    { char: '🐌', name: 'snail' },
    { char: '🦋', name: 'butterfly' },
    { char: '🐛', name: 'bug' },
    { char: '🐜', name: 'ant' },
    { char: '🐝', name: 'honeybee' },
    { char: '🪲', name: 'beetle' },
    { char: '🐞', name: 'lady beetle' },
    { char: '🦗', name: 'cricket' },
    { char: '🪳', name: 'cockroach' },
    { char: '🕷️', name: 'spider' },
    { char: '🕸️', name: 'spider web' },
    { char: '🦂', name: 'scorpion' },
    { char: '🦟', name: 'mosquito' },
    { char: '🪰', name: 'fly' },
    { char: '🪱', name: 'worm' },
    { char: '🦠', name: 'microbe' },
    { char: '💐', name: 'bouquet' },
    { char: '🌸', name: 'cherry blossom' },
    { char: '💮', name: 'white flower' },
    { char: '🏵️', name: 'rosette' },
    { char: '🌹', name: 'rose' },
    { char: '🥀', name: 'wilted flower' },
    { char: '🌺', name: 'hibiscus' },
    { char: '🌻', name: 'sunflower' },
    { char: '🌼', name: 'blossom' },
    { char: '🌷', name: 'tulip' },
    { char: '🌱', name: 'seedling' },
    { char: '🪴', name: 'potted plant' },
    { char: '🌲', name: 'evergreen tree' },
    { char: '🌳', name: 'deciduous tree' },
    { char: '🌴', name: 'palm tree' },
    { char: '🌵', name: 'cactus' },
    { char: '🌾', name: 'sheaf of rice' },
    { char: '🌿', name: 'herb' },
    { char: '☘️', name: 'shamrock' },
    { char: '🍀', name: 'four leaf clover' },
    { char: '🍁', name: 'maple leaf' },
    { char: '🍂', name: 'fallen leaf' },
    { char: '🍃', name: 'leaf fluttering in wind' },
    { char: '🪹', name: 'empty nest' },
    { char: '🪺', name: 'nest with eggs' }
    ],
    'Food & Drink': [
    { char: '🍎', name: 'red apple' },
    { char: '🍐', name: 'pear' },
    { char: '🍊', name: 'orange' },
    { char: '🍋', name: 'lemon' },
    { char: '🍌', name: 'banana' },
    { char: '🍉', name: 'watermelon' },
    { char: '🍇', name: 'grapes' },
    { char: '🍓', name: 'strawberry' },
    { char: '🫐', name: 'blueberries' },
    { char: '🍈', name: 'melon' },
    { char: '🍒', name: 'cherries' },
    { char: '🍑', name: 'peach' },
    { char: '🥭', name: 'mango' },
    { char: '🍍', name: 'pineapple' },
    { char: '🥥', name: 'coconut' },
    { char: '🥝', name: 'kiwi fruit' },
    { char: '🍅', name: 'tomato' },
    { char: '🫒', name: 'olive' },
    { char: '🥑', name: 'avocado' },
    { char: '🍆', name: 'eggplant' },
    { char: '🥔', name: 'potato' },
    { char: '🥕', name: 'carrot' },
    { char: '🌽', name: 'ear of corn' },
    { char: '🌶️', name: 'hot pepper' },
    { char: '🫑', name: 'bell pepper' },
    { char: '🥒', name: 'cucumber' },
    { char: '🥬', name: 'leafy green' },
    { char: '🥦', name: 'broccoli' },
    { char: '🧄', name: 'garlic' },
    { char: '🧅', name: 'onion' },
    { char: '🍄', name: 'mushroom' },
    { char: '🥜', name: 'peanuts' },
    { char: '🫘', name: 'beans' },
    { char: '🌰', name: 'chestnut' },
    { char: '🍞', name: 'bread' },
    { char: '🥐', name: 'croissant' },
    { char: '🥖', name: 'baguette bread' },
    { char: '🫓', name: 'flatbread' },
    { char: '🥨', name: 'pretzel' },
    { char: '🥯', name: 'bagel' },
    { char: '🥞', name: 'pancakes' },
    { char: '🧇', name: 'waffle' },
    { char: '🧀', name: 'cheese wedge' },
    { char: '🍖', name: 'meat on bone' },
    { char: '🍗', name: 'poultry leg' },
    { char: '🥩', name: 'cut of meat' },
    { char: '🥓', name: 'bacon' },
    { char: '🍔', name: 'hamburger' },
    { char: '🍟', name: 'french fries' },
    { char: '🍕', name: 'pizza' },
    { char: '🌭', name: 'hot dog' },
    { char: '🥪', name: 'sandwich' },
    { char: '🌮', name: 'taco' },
    { char: '🌯', name: 'burrito' },
    { char: '🫔', name: 'tamale' },
    { char: '🥙', name: 'stuffed flatbread' },
    { char: '🧆', name: 'falafel' },
    { char: '🥚', name: 'egg' },
    { char: '🍳', name: 'cooking' },
    { char: '🥘', name: 'shallow pan of food' },
    { char: '🍲', name: 'pot of food' },
    { char: '🫕', name: 'fondue' },
    { char: '🥣', name: 'bowl with spoon' },
    { char: '🥗', name: 'green salad' },
    { char: '🍿', name: 'popcorn' },
    { char: '🧈', name: 'butter' },
    { char: '🧂', name: 'salt' },
    { char: '🥫', name: 'canned food' },
    { char: '🍝', name: 'spaghetti' },
    { char: '🍜', name: 'steaming bowl' },
    { char: '🍠', name: 'roasted sweet potato' },
    { char: '🍢', name: 'oden' },
    { char: '🍣', name: 'sushi' },
    { char: '🍤', name: 'fried shrimp' },
    { char: '🍥', name: 'fish cake with swirl' },
    { char: '🥮', name: 'moon cake' },
    { char: '🍡', name: 'dango' },
    { char: '🥟', name: 'dumpling' },
    { char: '🥠', name: 'fortune cookie' },
    { char: '🥡', name: 'takeout box' },
    { char: '🍦', name: 'soft ice cream' },
    { char: '🍧', name: 'shaved ice' },
    { char: '🍨', name: 'ice cream' },
    { char: '🍩', name: 'doughnut' },
    { char: '🍪', name: 'cookie' },
    { char: '🎂', name: 'birthday cake' },
    { char: '🍰', name: 'shortcake' },
    { char: '🧁', name: 'cupcake' },
    { char: '🥧', name: 'pie' },
    { char: '🍫', name: 'chocolate bar' },
    { char: '🍬', name: 'candy' },
    { char: '🍭', name: 'lollipop' },
    { char: '🍮', name: 'custard' },
    { char: '🍯', name: 'honey pot' },
    { char: '🍼', name: 'baby bottle' },
    { char: '🥛', name: 'glass of milk' },
    { char: '☕', name: 'hot beverage' },
    { char: '🫖', name: 'teapot' },
    { char: '🍵', name: 'teacup without handle' },
    { char: '🍶', name: 'sake' },
    { char: '🍾', name: 'bottle with popping cork' },
    { char: '🍷', name: 'wine glass' },
    { char: '🍸', name: 'cocktail glass' },
    { char: '🍹', name: 'tropical drink' },
    { char: '🍺', name: 'beer mug' },
    { char: '🍻', name: 'clinking beer mugs' },
    { char: '🥂', name: 'clinking glasses' },
    { char: '🥃', name: 'tumbler glass' },
    { char: '🫗', name: 'pouring liquid' },
    { char: '🥤', name: 'cup with straw' },
    { char: '🧋', name: 'bubble tea' },
    { char: '🧃', name: 'beverage box' },
    { char: '🧉', name: 'mate' },
    { char: '🧊', name: 'ice' }
    ],
    'Travel & Places': [
    { char: '🌍', name: 'globe showing Europe-Africa' },
    { char: '🌎', name: 'globe showing Americas' },
    { char: '🌏', name: 'globe showing Asia-Australia' },
    { char: '🌐', name: 'globe with meridians' },
    { char: '🗺️', name: 'world map' },
    { char: '🗾', name: 'map of Japan' },
    { char: '🏔️', name: 'snow-capped mountain' },
    { char: '⛰️', name: 'mountain' },
    { char: '🌋', name: 'volcano' },
    { char: '🗻', name: 'mount fuji' },
    { char: '🏕️', name: 'camping' },
    { char: '🏖️', name: 'beach with umbrella' },
    { char: '🏜️', name: 'desert' },
    { char: '🏝️', name: 'desert island' },
    { char: '🏞️', name: 'national park' },
    { char: '🏟️', name: 'stadium' },
    { char: '🏛️', name: 'classical building' },
    { char: '🏗️', name: 'building construction' },
    { char: '🧱', name: 'brick' },
    { char: '🪨', name: 'rock' },
    { char: '🪵', name: 'wood' },
    { char: '🛖', name: 'hut' },
    { char: '🏘️', name: 'houses' },
    { char: '🏚️', name: 'derelict house' },
    { char: '🏠', name: 'house' },
    { char: '🏡', name: 'house with garden' },
    { char: '🏢', name: 'office building' },
    { char: '🏣', name: 'Japanese post office' },
    { char: '🏤', name: 'post office' },
    { char: '🏥', name: 'hospital' },
    { char: '🏦', name: 'bank' },
    { char: '🏨', name: 'hotel' },
    { char: '🏩', name: 'love hotel' },
    { char: '🏪', name: 'convenience store' },
    { char: '🏫', name: 'school' },
    { char: '🏬', name: 'department store' },
    { char: '🏭', name: 'factory' },
    { char: '🏯', name: 'Japanese castle' },
    { char: '🏰', name: 'castle' },
    { char: '💒', name: 'wedding' },
    { char: '🗼', name: 'Tokyo tower' },
    { char: '🗽', name: 'Statue of Liberty' },
    { char: '⛪', name: 'church' },
    { char: '🕌', name: 'mosque' },
    { char: '🕍', name: 'synagogue' },
    { char: '⛩️', name: 'shinto shrine' },
    { char: '🕋', name: 'kaaba' },
    { char: '⛲', name: 'fountain' },
    { char: '⛺', name: 'tent' },
    { char: '🌁', name: 'foggy' },
    { char: '🌃', name: 'night with stars' },
    { char: '🏙️', name: 'cityscape' },
    { char: '🌄', name: 'sunrise over mountains' },
    { char: '🌅', name: 'sunrise' },
    { char: '🌆', name: 'cityscape at dusk' },
    { char: '🌇', name: 'sunset' },
    { char: '🌉', name: 'bridge at night' },
    { char: '♨️', name: 'hot springs' },
    { char: '🎠', name: 'carousel horse' },
    { char: '🛝', name: 'playground slide' },
    { char: '🎡', name: 'ferris wheel' },
    { char: '🎢', name: 'roller coaster' },
    { char: '💈', name: 'barber pole' },
    { char: '🎪', name: 'circus tent' },
    { char: '🚂', name: 'locomotive' },
    { char: '🚃', name: 'railway car' },
    { char: '🚄', name: 'high-speed train' },
    { char: '🚅', name: 'bullet train' },
    { char: '🚆', name: 'train' },
    { char: '🚇', name: 'metro' },
    { char: '🚈', name: 'light rail' },
    { char: '🚉', name: 'station' },
    { char: '🚊', name: 'tram' },
    { char: '🚝', name: 'monorail' },
    { char: '🚞', name: 'mountain railway' },
    { char: '🚋', name: 'tram car' },
    { char: '🚌', name: 'bus' },
    { char: '🚍', name: 'oncoming bus' },
    { char: '🚎', name: 'trolleybus' },
    { char: '🚐', name: 'minibus' },
    { char: '🚑', name: 'ambulance' },
    { char: '🚒', name: 'fire engine' },
    { char: '🚓', name: 'police car' },
    { char: '🚔', name: 'oncoming police car' },
    { char: '🚕', name: 'taxi' },
    { char: '🚖', name: 'oncoming taxi' },
    { char: '🚗', name: 'automobile' },
    { char: '🚘', name: 'oncoming automobile' },
    { char: '🚙', name: 'sport utility vehicle' },
    { char: '🛻', name: 'pickup truck' },
    { char: '🚚', name: 'delivery truck' },
    { char: '🚛', name: 'articulated lorry' },
    { char: '🚜', name: 'tractor' },
    { char: '🏎️', name: 'racing car' },
    { char: '🏍️', name: 'motorcycle' },
    { char: '🛵', name: 'motor scooter' },
    { char: '🦽', name: 'manual wheelchair' },
    { char: '🦼', name: 'motorized wheelchair' },
    { char: '🛺', name: 'auto rickshaw' },
    { char: '🚲', name: 'bicycle' },
    { char: '🛴', name: 'kick scooter' },
    { char: '🛹', name: 'skateboard' },
    { char: '🛼', name: 'roller skate' },
    { char: '🚏', name: 'bus stop' },
    { char: '🛣️', name: 'motorway' },
    { char: '🛤️', name: 'railway track' },
    { char: '🛢️', name: 'oil drum' },
    { char: '⛽', name: 'fuel pump' },
    { char: '🚨', name: 'police car light' },
    { char: '🚥', name: 'horizontal traffic light' },
    { char: '🚦', name: 'vertical traffic light' },
    { char: '🛑', name: 'stop sign' },
    { char: '🚧', name: 'construction' },
    { char: '⚓', name: 'anchor' },
    { char: '⛵', name: 'sailboat' },
    { char: '🛶', name: 'canoe' },
    { char: '🚤', name: 'speedboat' },
    { char: '🛳️', name: 'passenger ship' },
    { char: '⛴️', name: 'ferry' },
    { char: '🛥️', name: 'motor boat' },
    { char: '🚢', name: 'ship' },
    { char: '✈️', name: 'airplane' },
    { char: '🛩️', name: 'small airplane' },
    { char: '🛫', name: 'airplane departure' },
    { char: '🛬', name: 'airplane arrival' },
    { char: '🪂', name: 'parachute' },
    { char: '💺', name: 'seat' },
    { char: '🚁', name: 'helicopter' },
    { char: '🚟', name: 'suspension railway' },
    { char: '🚠', name: 'mountain cableway' },
    { char: '🚡', name: 'aerial tramway' },
    { char: '🛰️', name: 'satellite' },
    { char: '🚀', name: 'rocket' },
    { char: '🛸', name: 'flying saucer' },
    { char: '🛎️', name: 'bellhop bell' },
    { char: '🧳', name: 'luggage' },
    { char: '⌛', name: 'hourglass done' },
    { char: '⏳', name: 'hourglass not done' },
    { char: '⌚', name: 'watch' },
    { char: '⏰', name: 'alarm clock' },
    { char: '⏱️', name: 'stopwatch' },
    { char: '⏲️', name: 'timer clock' },
    { char: '🕰️', name: 'mantelpiece clock' },
    { char: '🕛', name: 'twelve oclock' },
    { char: '🕧', name: 'twelve-thirty' }
    ],
    'Activities': [
    { char: '🎯', name: 'direct hit' },
    { char: '🎱', name: 'pool 8 ball' },
    { char: '🎮', name: 'video game' },
    { char: '🎲', name: 'game die' },
    { char: '🧩', name: 'puzzle piece' },
    { char: '🎨', name: 'artist palette' },
    { char: '🎭', name: 'performing arts' },
    { char: '🎪', name: 'circus tent' },
    { char: '🎤', name: 'microphone' },
    { char: '🎧', name: 'headphone' },
    { char: '🎼', name: 'musical score' },
    { char: '🎹', name: 'musical keyboard' },
    { char: '🥁', name: 'drum' },
    { char: '🎷', name: 'saxophone' },
    { char: '🎺', name: 'trumpet' },
    { char: '🎸', name: 'guitar' },
    { char: '🪕', name: 'banjo' },
    { char: '🎻', name: 'violin' },
    { char: '🎬', name: 'clapper board' },
    { char: '🏹', name: 'bow and arrow' },
    { char: '🎣', name: 'fishing pole' },
    { char: '🤿', name: 'diving mask' },
    { char: '🎽', name: 'running shirt' },
    { char: '🎿', name: 'skis' },
    { char: '🛷', name: 'sled' },
    { char: '🥌', name: 'curling stone' },
    { char: '🎯', name: 'bullseye' },
    { char: '🎳', name: 'bowling' },
    { char: '🎮', name: 'video game controller' },
    { char: '🎲', name: 'game die' },
    { char: '♟️', name: 'chess pawn' },
    { char: '🎭', name: 'performing arts' },
    { char: '🎪', name: 'circus tent' },
    { char: '🎨', name: 'artist palette' },
    { char: '🧵', name: 'thread' },
    { char: '🪡', name: 'sewing needle' },
    { char: '🧶', name: 'yarn' },
    { char: '🎨', name: 'artist palette' },
    { char: '🎭', name: 'performing arts' },
    ],
    'Objects': [
    { char: '⌚', name: 'watch' },
    { char: '📱', name: 'mobile phone' },
    { char: '📲', name: 'mobile phone with arrow' },
    { char: '💻', name: 'laptop' },
    { char: '⌨️', name: 'keyboard' },
    { char: '🖥️', name: 'desktop computer' },
    { char: '🖨️', name: 'printer' },
    { char: '🖱️', name: 'computer mouse' },
    { char: '🖲️', name: 'trackball' },
    { char: '🕹️', name: 'joystick' },
    { char: '🗜️', name: 'clamp' },
    { char: '💽', name: 'computer disk' },
    { char: '💾', name: 'floppy disk' },
    { char: '💿', name: 'optical disk' },
    { char: '📀', name: 'dvd' },
    { char: '📼', name: 'videocassette' },
    { char: '📷', name: 'camera' },
    { char: '📸', name: 'camera with flash' },
    { char: '📹', name: 'video camera' },
    { char: '🎥', name: 'movie camera' },
    { char: '📽️', name: 'film projector' },
    { char: '🎞️', name: 'film frames' },
    { char: '📞', name: 'telephone receiver' },
    { char: '☎️', name: 'telephone' },
    { char: '📟', name: 'pager' },
    { char: '📠', name: 'fax machine' },
    { char: '📺', name: 'television' },
    { char: '📻', name: 'radio' },
    { char: '🎙️', name: 'studio microphone' },
    { char: '🎚️', name: 'level slider' },
    { char: '🎛️', name: 'control knobs' },
    { char: '🧭', name: 'compass' },
    { char: '⏰', name: 'alarm clock' },
    { char: '⏱️', name: 'stopwatch' },
    { char: '⏲️', name: 'timer clock' },
    { char: '⌛', name: 'hourglass' },
    { char: '⏳', name: 'hourglass flowing' },
    { char: '📡', name: 'satellite antenna' },
    { char: '🔋', name: 'battery' },
    { char: '🔌', name: 'electric plug' },
    { char: '💡', name: 'light bulb' },
    { char: '🔦', name: 'flashlight' },
    { char: '🕯️', name: 'candle' },
    { char: '🗑️', name: 'wastebasket' },
    { char: '🛢️', name: 'oil drum' },
    { char: '💸', name: 'money with wings' },
    { char: '💵', name: 'dollar banknote' },
    { char: '💴', name: 'yen banknote' },
    { char: '💶', name: 'euro banknote' },
    { char: '💷', name: 'pound banknote' },
    { char: '💰', name: 'money bag' },
    { char: '💳', name: 'credit card' },
    { char: '💎', name: 'gem stone' },
    { char: '⚖️', name: 'balance scale' },
    { char: '🔧', name: 'wrench' },
    { char: '🔨', name: 'hammer' },
    { char: '⚒️', name: 'hammer and pick' },
    { char: '🛠️', name: 'hammer and wrench' },
    { char: '⛏️', name: 'pick' },
    { char: '🔩', name: 'nut and bolt' },
    { char: '⚙️', name: 'gear' },
    { char: '🗡️', name: 'dagger' },
    { char: '⚔️', name: 'crossed swords' },
    { char: '🔫', name: 'water pistol' },
    { char: '🛡️', name: 'shield' },
    { char: '🔧', name: 'wrench' },
    { char: '🔨', name: 'hammer' },
    { char: '⚒️', name: 'hammer and pick' },
    { char: '🛠️', name: 'hammer and wrench' },
    { char: '⛏️', name: 'pick' },
    { char: '✂️', name: 'scissors' },
    { char: '🔍', name: 'magnifying glass left' },
    { char: '🔎', name: 'magnifying glass right' },
    { char: '🔮', name: 'crystal ball' },
    { char: '📿', name: 'prayer beads' },
    { char: '🧿', name: 'nazar amulet' },
    { char: '💈', name: 'barber pole' },
    { char: '⚗️', name: 'alembic' },
    { char: '🔭', name: 'telescope' },
    { char: '🔬', name: 'microscope' },
    { char: '📡', name: 'satellite antenna' }
    ],
    'Symbols': [
    { char: '💟', name: 'heart decoration' },
    { char: '☮️', name: 'peace symbol' },
    { char: '✝️', name: 'latin cross' },
    { char: '☪️', name: 'star and crescent' },
    { char: '🕉️', name: 'om' },
    { char: '☸️', name: 'wheel of dharma' },
    { char: '✡️', name: 'star of david' },
    { char: '🔯', name: 'dotted six-pointed star' },
    { char: '🕎', name: 'menorah' },
    { char: '☯️', name: 'yin yang' },
    { char: '☦️', name: 'orthodox cross' },
    { char: '🛐', name: 'place of worship' },
    { char: '⚛️', name: 'atom symbol' },
    { char: '🕉️', name: 'om' },
    { char: '✡️', name: 'star of david' },
    { char: '☸️', name: 'wheel of dharma' },
    { char: '☯️', name: 'yin yang' },
    { char: '✝️', name: 'latin cross' },
    { char: '☦️', name: 'orthodox cross' },
    { char: '☪️', name: 'star and crescent' },
    { char: '☮️', name: 'peace symbol' },
    { char: '🕎', name: 'menorah' },
    { char: '🔯', name: 'dotted six-pointed star' },
    { char: '♈', name: 'aries' },
    { char: '♉', name: 'taurus' },
    { char: '♊', name: 'gemini' },
    { char: '♋', name: 'cancer' },
    { char: '♌', name: 'leo' },
    { char: '♍', name: 'virgo' },
    { char: '♎', name: 'libra' },
    { char: '♏', name: 'scorpio' },
    { char: '♐', name: 'sagittarius' },
    { char: '♑', name: 'capricorn' },
    { char: '♒', name: 'aquarius' },
    { char: '♓', name: 'pisces' },
    { char: '⛎', name: 'ophiuchus' },
    { char: '🔀', name: 'shuffle tracks button' },
    { char: '🔁', name: 'repeat button' },
    { char: '🔂', name: 'repeat single button' },
    { char: '▶️', name: 'play button' },
    { char: '⏩', name: 'fast-forward button' },
    { char: '⏭️', name: 'next track button' },
    { char: '⏯️', name: 'play or pause button' },
    { char: '◀️', name: 'reverse button' },
    { char: '⏪', name: 'fast reverse button' },
    { char: '⏮️', name: 'last track button' },
    { char: '🔼', name: 'upwards button' },
    { char: '⏫', name: 'fast up button' },
    { char: '🔽', name: 'downwards button' },
    { char: '⏬', name: 'fast down button' },
    { char: '⏸️', name: 'pause button' },
    { char: '⏹️', name: 'stop button' },
    { char: '⏺️', name: 'record button' },
    { char: '⏏️', name: 'eject button' },
    { char: '🎦', name: 'cinema' },
    { char: '🔅', name: 'dim button' },
    { char: '🔆', name: 'bright button' },
    { char: '📶', name: 'antenna bars' },
    { char: '📳', name: 'vibration mode' },
    { char: '📴', name: 'mobile phone off' },
    { char: '♀️', name: 'female sign' },
    { char: '♂️', name: 'male sign' },
    { char: '⚧️', name: 'transgender symbol' },
    { char: '✖️', name: 'multiply' },
    { char: '➕', name: 'plus' },
    { char: '➖', name: 'minus' },
    { char: '➗', name: 'divide' },
    { char: '♾️', name: 'infinity' },
    { char: '‼️', name: 'double exclamation mark' },
    { char: '⁉️', name: 'exclamation question mark' },
    { char: '❓', name: 'red question mark' },
    { char: '❔', name: 'white question mark' },
    { char: '❕', name: 'white exclamation mark' },
    { char: '❗', name: 'red exclamation mark' },
    ],
    'Flags': [
    { char: '🏁', name: 'chequered flag' },
    { char: '🚩', name: 'triangular flag' },
    { char: '🎌', name: 'crossed flags' },
    { char: '🏳️', name: 'white flag' },
    { char: '🏳️‍🌈', name: 'rainbow flag' },
    { char: '🏳️‍⚧️', name: 'transgender flag' },
    { char: '🏴', name: 'black flag' },
    { char: '🏴‍☠️', name: 'pirate flag' },
    { char: '🇦🇨', name: 'flag: Ascension Island' },
    { char: '🇦🇩', name: 'flag: Andorra' },
    { char: '🇦🇪', name: 'flag: United Arab Emirates' },
    { char: '🇦🇫', name: 'flag: Afghanistan' },
    { char: '🇦🇬', name: 'flag: Antigua & Barbuda' },
    { char: '🇦🇮', name: 'flag: Anguilla' },
    { char: '🇦🇱', name: 'flag: Albania' },
    { char: '🇦🇲', name: 'flag: Armenia' },
    { char: '🇦🇴', name: 'flag: Angola' },
    { char: '🇦🇶', name: 'flag: Antarctica' },
    { char: '🇦🇷', name: 'flag: Argentina' },
    { char: '🇦🇸', name: 'flag: American Samoa' },
    { char: '🇦🇹', name: 'flag: Austria' },
    { char: '🇦🇺', name: 'flag: Australia' },
    { char: '🇦🇼', name: 'flag: Aruba' },
    { char: '🇦🇽', name: 'flag: Åland Islands' },
    { char: '🇦🇿', name: 'flag: Azerbaijan' },
    { char: '🇧🇦', name: 'flag: Bosnia & Herzegovina' },
    { char: '🇧🇧', name: 'flag: Barbados' },
    { char: '🇧🇩', name: 'flag: Bangladesh' },
    { char: '🇧🇪', name: 'flag: Belgium' },
    { char: '🇧🇫', name: 'flag: Burkina Faso' },
    { char: '🇧🇬', name: 'flag: Bulgaria' },
    { char: '🇧🇭', name: 'flag: Bahrain' },
    { char: '🇧🇮', name: 'flag: Burundi' },
    { char: '🇧🇯', name: 'flag: Benin' },
    { char: '🇧🇱', name: 'flag: St. Barthélemy' },
    { char: '🇧🇲', name: 'flag: Bermuda' },
    { char: '🇧🇳', name: 'flag: Brunei' },
    { char: '🇧🇴', name: 'flag: Bolivia' },
    { char: '🇧🇶', name: 'flag: Caribbean Netherlands' },
    { char: '🇧🇷', name: 'flag: Brazil' },
    { char: '🇧🇸', name: 'flag: Bahamas' },
    { char: '🇧🇹', name: 'flag: Bhutan' },
    { char: '🇧🇻', name: 'flag: Bouvet Island' },
    { char: '🇧🇼', name: 'flag: Botswana' },
    { char: '🇧🇾', name: 'flag: Belarus' },
    { char: '🇧🇿', name: 'flag: Belize' },
    { char: '🇨🇦', name: 'flag: Canada' },
    { char: '🇨🇨', name: 'flag: Cocos (Keeling) Islands' },
    { char: '🇨🇩', name: 'flag: Congo - Kinshasa' },
    { char: '🇨🇫', name: 'flag: Central African Republic' },
    { char: '🇨🇬', name: 'flag: Congo - Brazzaville' },
    { char: '🇨🇭', name: 'flag: Switzerland' },
    { char: '🇨🇮', name: 'flag: Côte d\'Ivoire' },
    { char: '🇨🇰', name: 'flag: Cook Islands' },
    { char: '🇨🇱', name: 'flag: Chile' },
    { char: '🇨🇲', name: 'flag: Cameroon' },
    { char: '🇨🇳', name: 'flag: China' },
    { char: '🇨🇴', name: 'flag: Colombia' },
    { char: '🇨🇵', name: 'flag: Clipperton Island' },
    { char: '🇨🇷', name: 'flag: Costa Rica' },
    { char: '🇨🇺', name: 'flag: Cuba' },
    { char: '🇨🇻', name: 'flag: Cape Verde' },
    { char: '🇨🇼', name: 'flag: Curaçao' },
    { char: '🇨🇽', name: 'flag: Christmas Island' },
    { char: '🇨🇾', name: 'flag: Cyprus' },
    { char: '🇨🇿', name: 'flag: Czechia' },
    { char: '🇩🇪', name: 'flag: Germany' },
    { char: '🇩🇬', name: 'flag: Diego Garcia' },
    { char: '🇩🇯', name: 'flag: Djibouti' },
    { char: '🇩🇰', name: 'flag: Denmark' },
    { char: '🇩🇲', name: 'flag: Dominica' },
    { char: '🇩🇴', name: 'flag: Dominican Republic' },
    { char: '🇩🇿', name: 'flag: Algeria' },
    { char: '🇪🇦', name: 'flag: Ceuta & Melilla' },
    { char: '🇪🇨', name: 'flag: Ecuador' },
    { char: '🇪🇪', name: 'flag: Estonia' },
    { char: '🇪🇬', name: 'flag: Egypt' },
    { char: '🇪🇭', name: 'flag: Western Sahara' },
    { char: '🇪🇷', name: 'flag: Eritrea' },
    { char: '🇪🇸', name: 'flag: Spain' },
    { char: '🇪🇹', name: 'flag: Ethiopia' },
    { char: '🇪🇺', name: 'flag: European Union' },
    { char: '🇫🇮', name: 'flag: Finland' },
    { char: '🇫🇯', name: 'flag: Fiji' },
    { char: '🇫🇰', name: 'flag: Falkland Islands' },
    { char: '🇫🇲', name: 'flag: Micronesia' },
    { char: '🇫🇴', name: 'flag: Faroe Islands' },
    { char: '🇫🇷', name: 'flag: France' },
    { char: '🇬🇦', name: 'flag: Gabon' },
    { char: '🇬🇧', name: 'flag: United Kingdom' },
    { char: '🇬🇩', name: 'flag: Grenada' },
    { char: '🇬🇪', name: 'flag: Georgia' },
    { char: '🇬🇫', name: 'flag: French Guiana' },
    { char: '🇬🇬', name: 'flag: Guernsey' },
    { char: '🇬🇭', name: 'flag: Ghana' },
    { char: '🇬🇮', name: 'flag: Gibraltar' },
    { char: '🇬🇱', name: 'flag: Greenland' },
    { char: '🇬🇲', name: 'flag: Gambia' },
    { char: '🇬🇳', name: 'flag: Guinea' },
    { char: '🇬🇵', name: 'flag: Guadeloupe' },
    { char: '🇬🇶', name: 'flag: Equatorial Guinea' },
    { char: '🇬🇷', name: 'flag: Greece' },
    { char: '🇬🇸', name: 'flag: South Georgia & South Sandwich Islands' },
    { char: '🇬🇹', name: 'flag: Guatemala' },
    { char: '🇬🇺', name: 'flag: Guam' },
    { char: '🇬🇼', name: 'flag: Guinea-Bissau' },
    { char: '🇬🇾', name: 'flag: Guyana' },
    { char: '🇭🇰', name: 'flag: Hong Kong SAR China' },
    { char: '🇭🇲', name: 'flag: Heard & McDonald Islands' },
    { char: '🇭🇳', name: 'flag: Honduras' },
    { char: '🇭🇷', name: 'flag: Croatia' },
    { char: '🇭🇹', name: 'flag: Haiti' },
    { char: '🇭🇺', name: 'flag: Hungary' },
    { char: '🇮🇨', name: 'flag: Canary Islands' },
    { char: '🇮🇩', name: 'flag: Indonesia' },
    { char: '🇮🇪', name: 'flag: Ireland' },
    { char: '🇮🇱', name: 'flag: Israel' },
    { char: '🇮🇲', name: 'flag: Isle of Man' },
    { char: '🇮🇳', name: 'flag: India' },
    { char: '🇮🇴', name: 'flag: British Indian Ocean Territory' },
    { char: '🇮🇶', name: 'flag: Iraq' },
    { char: '🇮🇷', name: 'flag: Iran' },
    { char: '🇮🇸', name: 'flag: Iceland' },
    { char: '🇮🇹', name: 'flag: Italy' },
    { char: '🇯🇪', name: 'flag: Jersey' },
    { char: '🇯🇲', name: 'flag: Jamaica' },
    { char: '🇯🇴', name: 'flag: Jordan' },
    { char: '🇯🇵', name: 'flag: Japan' },
    { char: '🇰🇪', name: 'flag: Kenya' },
    { char: '🇰🇬', name: 'flag: Kyrgyzstan' },
    { char: '🇰🇭', name: 'flag: Cambodia' },
    { char: '🇰🇮', name: 'flag: Kiribati' },
    { char: '🇰🇲', name: 'flag: Comoros' },
    { char: '🇰🇳', name: 'flag: St. Kitts & Nevis' },
    { char: '🇰🇵', name: 'flag: North Korea' },
    { char: '🇰🇷', name: 'flag: South Korea' },
    { char: '🇰🇼', name: 'flag: Kuwait' },
    { char: '🇰🇾', name: 'flag: Cayman Islands' },
    { char: '🇰🇿', name: 'flag: Kazakhstan' },
    { char: '🇱🇦', name: 'flag: Laos' },
    { char: '🇱🇧', name: 'flag: Lebanon' },
    { char: '🇱🇨', name: 'flag: St. Lucia' },
    { char: '🇱🇮', name: 'flag: Liechtenstein' },
    { char: '🇱🇰', name: 'flag: Sri Lanka' },
    { char: '🇱🇷', name: 'flag: Liberia' },
    { char: '🇱🇸', name: 'flag: Lesotho' },
    { char: '🇱🇹', name: 'flag: Lithuania' },
    { char: '🇱🇺', name: 'flag: Luxembourg' },
    { char: '🇱🇻', name: 'flag: Latvia' },
    { char: '🇱🇾', name: 'flag: Libya' },
    { char: '🇲🇦', name: 'flag: Morocco' },
    { char: '🇲🇨', name: 'flag: Monaco' },
    { char: '🇲🇩', name: 'flag: Moldova' },
    { char: '🇲🇪', name: 'flag: Montenegro' },
    { char: '🇲🇫', name: 'flag: St. Martin' },
    { char: '🇲🇬', name: 'flag: Madagascar' },
    { char: '🇲🇭', name: 'flag: Marshall Islands' },
    { char: '🇲🇰', name: 'flag: North Macedonia' },
    { char: '🇲🇱', name: 'flag: Mali' },
    { char: '🇲🇲', name: 'flag: Myanmar (Burma)' },
    { char: '🇲🇳', name: 'flag: Mongolia' },
    { char: '🇲🇴', name: 'flag: Macao SAR China' },
    { char: '🇲🇵', name: 'flag: Northern Mariana Islands' },
    { char: '🇲🇶', name: 'flag: Martinique' },
    { char: '🇲🇷', name: 'flag: Mauritania' },
    { char: '🇲🇸', name: 'flag: Montserrat' },
    { char: '🇲🇹', name: 'flag: Malta' },
    { char: '🇲🇺', name: 'flag: Mauritius' },
    { char: '🇲🇻', name: 'flag: Maldives' },
    { char: '🇲🇼', name: 'flag: Malawi' },
    { char: '🇲🇽', name: 'flag: Mexico' },
    { char: '🇲🇾', name: 'flag: Malaysia' },
    { char: '🇲🇿', name: 'flag: Mozambique' },
    { char: '🇳🇦', name: 'flag: Namibia' },
    { char: '🇳🇨', name: 'flag: New Caledonia' },
    { char: '🇳🇪', name: 'flag: Niger' },
    { char: '🇳🇫', name: 'flag: Norfolk Island' },
    { char: '🇳🇬', name: 'flag: Nigeria' },
    { char: '🇳🇮', name: 'flag: Nicaragua' },
    { char: '🇳🇱', name: 'flag: Netherlands' },
    { char: '🇳🇴', name: 'flag: Norway' },
    { char: '🇳🇵', name: 'flag: Nepal' },
    { char: '🇳🇷', name: 'flag: Nauru' },
    { char: '🇳🇺', name: 'flag: Niue' },
    { char: '🇳🇿', name: 'flag: New Zealand' },
    { char: '🇴🇲', name: 'flag: Oman' },
    { char: '🇵🇦', name: 'flag: Panama' },
    { char: '🇵🇪', name: 'flag: Peru' },
    { char: '🇵🇫', name: 'flag: French Polynesia' },
    { char: '🇵🇬', name: 'flag: Papua New Guinea' },
    { char: '🇵🇭', name: 'flag: Philippines' },
    { char: '🇵🇰', name: 'flag: Pakistan' },
    { char: '🇵🇱', name: 'flag: Poland' },
    { char: '🇵🇲', name: 'flag: St. Pierre & Miquelon' },
    { char: '🇵🇳', name: 'flag: Pitcairn Islands' },
    { char: '🇵🇷', name: 'flag: Puerto Rico' },
    { char: '🇵🇸', name: 'flag: Palestinian Territories' },
    { char: '🇵🇹', name: 'flag: Portugal' },
    { char: '🇵🇼', name: 'flag: Palau' },
    { char: '🇵🇾', name: 'flag: Paraguay' },
    { char: '🇶🇦', name: 'flag: Qatar' },
    { char: '🇷🇪', name: 'flag: Réunion' },
    { char: '🇷🇴', name: 'flag: Romania' },
    { char: '🇷🇸', name: 'flag: Serbia' },
    { char: '🇷🇺', name: 'flag: Russia' },
    { char: '🇷🇼', name: 'flag: Rwanda' },
    { char: '🇸🇦', name: 'flag: Saudi Arabia' },
    { char: '🇸🇧', name: 'flag: Solomon Islands' },
    { char: '🇸🇨', name: 'flag: Seychelles' },
    { char: '🇸🇩', name: 'flag: Sudan' },
    { char: '🇸🇪', name: 'flag: Sweden' },
    { char: '🇸🇬', name: 'flag: Singapore' },
    { char: '🇸🇭', name: 'flag: St. Helena' },
    { char: '🇸🇮', name: 'flag: Slovenia' },
    { char: '🇸🇯', name: 'flag: Svalbard & Jan Mayen' },
    { char: '🇸🇰', name: 'flag: Slovakia' },
    { char: '🇸🇱', name: 'flag: Sierra Leone' },
    { char: '🇸🇲', name: 'flag: San Marino' },
    { char: '🇸🇳', name: 'flag: Senegal' },
    { char: '🇸🇴', name: 'flag: Somalia' },
    { char: '🇸🇷', name: 'flag: Suriname' },
    { char: '🇸🇸', name: 'flag: South Sudan' },
    { char: '🇸🇹', name: 'flag: São Tomé & Príncipe' },
    { char: '🇸🇻', name: 'flag: El Salvador' },
    { char: '🇸🇽', name: 'flag: Sint Maarten' },
    { char: '🇸🇾', name: 'flag: Syria' },
    { char: '🇸🇿', name: 'flag: Eswatini' },
    { char: '🇹🇦', name: 'flag: Tristan da Cunha' },
    { char: '🇹🇨', name: 'flag: Turks & Caicos Islands' },
    { char: '🇹🇩', name: 'flag: Chad' },
    { char: '🇹🇫', name: 'flag: French Southern Territories' },
    { char: '🇹🇬', name: 'flag: Togo' },
    { char: '🇹🇭', name: 'flag: Thailand' },
    { char: '🇹🇯', name: 'flag: Tajikistan' },
    { char: '🇹🇰', name: 'flag: Tokelau' },
    { char: '🇹🇱', name: 'flag: Timor-Leste' },
    { char: '🇹🇲', name: 'flag: Turkmenistan' },
    { char: '🇹🇳', name: 'flag: Tunisia' },
    { char: '🇹🇴', name: 'flag: Tonga' },
    { char: '🇹🇷', name: 'flag: Turkey' },
    { char: '🇹🇹', name: 'flag: Trinidad & Tobago' },
    { char: '🇹🇻', name: 'flag: Tuvalu' },
    { char: '🇹🇼', name: 'flag: Taiwan' },
    { char: '🇹🇿', name: 'flag: Tanzania' },
    { char: '🇺🇦', name: 'flag: Ukraine' },
    { char: '🇺🇬', name: 'flag: Uganda' },
    { char: '🇺🇲', name: 'flag: U.S. Outlying Islands' },
    { char: '🇺🇳', name: 'flag: United Nations' },
    { char: '🇺🇸', name: 'flag: United States' },
    { char: '🇺🇾', name: 'flag: Uruguay' },
    { char: '🇺🇿', name: 'flag: Uzbekistan' },
    { char: '🇻🇦', name: 'flag: Vatican City' },
    { char: '🇻🇨', name: 'flag: St. Vincent & Grenadines' },
    { char: '🇻🇪', name: 'flag: Venezuela' },
    { char: '🇻🇬', name: 'flag: British Virgin Islands' },
    { char: '🇻🇮', name: 'flag: U.S. Virgin Islands' },
    { char: '🇻🇳', name: 'flag: Vietnam' },
    { char: '🇻🇺', name: 'flag: Vanuatu' },
    { char: '🇼🇫', name: 'flag: Wallis & Futuna' },
    { char: '🇼🇸', name: 'flag: Samoa' },
    { char: '🇽🇰', name: 'flag: Kosovo' },
    { char: '🇾🇪', name: 'flag: Yemen' },
    { char: '🇾🇹', name: 'flag: Mayotte' },
    { char: '🇿🇦', name: 'flag: South Africa' },
    { char: '🇿🇲', name: 'flag: Zambia' },
    { char: '🇿🇼', name: 'flag: Zimbabwe' },
    ]
};
const container = document.getElementById('emoji-container');
const search = document.querySelector('.search');
const feedback = document.querySelector('.feedback');
const themeToggle = document.getElementById('theme-toggle');

function copyEmoji(char) {
navigator.clipboard.writeText(char).then(() => {
    feedback.style.display = 'block';
    setTimeout(() => {
        feedback.style.display = 'none';
    }, 1500);
}).catch(err => {
    console.error('Failed to copy:', err);
    feedback.textContent = 'Failed to copy 😕';
    feedback.style.display = 'block';
    setTimeout(() => {
        feedback.style.display = 'none';
        feedback.textContent = 'Copied! 📋';
    }, 1500);
});
}

function renderSearchResults(results) {
if (results.length === 0) {
    container.innerHTML = `
        <div class="no-results">
            No emojis found matching "${search.value}" 🔍
        </div>
    `;
    return;
}

const emojiGrid = document.createElement('div');
emojiGrid.className = 'emoji-grid';

results.forEach(({ char, name, category }) => {
    const card = document.createElement('div');
    card.className = 'emoji-card';
    card.innerHTML = `
        <div class="emoji">${char}</div>
        <div class="name">${name}</div>
        <div class="category-tag">${category}</div>
    `;
    card.onclick = () => copyEmoji(char);
    emojiGrid.appendChild(card);
});

container.innerHTML = '';
container.appendChild(emojiGrid);
}

function getCategoryId(category) {
return category.toLowerCase().split(' & ')[0].split(' ')[0];
}

function renderCategories() {
container.innerHTML = Object.entries(emojiCategories).map(([category, emojis]) => `
    <div class="category-section" id="${getCategoryId(category)}">
        <h2 class="category-title">${category}</h2>
        <div class="emoji-grid">
            ${emojis.map(emoji => `
                <div class="emoji-card" onclick="copyEmoji('${emoji.char}')">
                    <div class="emoji">${emoji.char}</div>
                    <div class="name">${emoji.name}</div>
                </div>
            `).join('')}
        </div>
    </div>
`).join('');
}

search.addEventListener('input', _.debounce(function(e) {
const value = e.target.value.toLowerCase();

if (!value.trim()) {
    renderCategories();
    return;
}

const results = Object.entries(emojiCategories).flatMap(([category, emojis]) => {
    return emojis
        .filter(emoji => 
            emoji.name.toLowerCase().includes(value) || 
            emoji.char.includes(value)
        )
        .map(emoji => ({...emoji, category}));
});

renderSearchResults(results);
}, 300));

themeToggle.addEventListener('click', () => {
const root = document.documentElement;
const currentTheme = root.getAttribute('data-theme');
const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
root.setAttribute('data-theme', newTheme);
localStorage.setItem('theme', newTheme);
});

// Initialize theme
const savedTheme = localStorage.getItem('theme');
if (savedTheme) {
document.documentElement.setAttribute('data-theme', savedTheme);
}

// Add category navigation
document.querySelectorAll('.category-link').forEach(link => {
link.addEventListener('click', (e) => {
    e.preventDefault();
    const id = e.currentTarget.getAttribute('href').substring(1);
    document.getElementById(id).scrollIntoView({ behavior: 'smooth' });
});
});

// Initial render
renderCategories();

// get date for footer
document.getElementById('date').textContent = new Date().getFullYear();